# -*- coding: utf-8 -*-
"""Migrate from legacy module name `llm_tool_web_research` and prune
stale xmlids that the renamed module no longer declares.

The legacy module shipped extra menus / actions / views that this
module no longer defines. A naive rename of ir_model_data leaves those
records behind as orphans (visible in the menu tree). The cleanup logic
is shared between pre_init_hook (fresh install on a legacy DB) and the
migration script (already-renamed DB with orphans).
"""

import logging

_logger = logging.getLogger(__name__)

OLD_NAME = 'llm_tool_web_research'
NEW_NAME = 'llm_tool_websearch'

# xmlids this module currently declares. Anything attributed to this
# module via ir_model_data outside this set is a leftover from the
# legacy module and must be pruned.
LEGITIMATE_XMLIDS = frozenset({
    # llm.tool
    'llm_tool_web_search',
    'llm_tool_web_fetch',
    # llm.prompt / llm.assistant
    'llm_prompt_web_researcher',
    'llm_assistant_web_researcher',
    # ui
    'view_websearch_test_form',
    'action_websearch_test',
    'menu_websearch_test',
    # security
    'access_llm_websearch_test',
    # auto-generated by ORM, kept for completeness
    'model_llm_websearch_test',
})


def _rename_legacy_module(cr):
    cr.execute("SELECT id FROM ir_module_module WHERE name = %s", (OLD_NAME,))
    if not cr.fetchone():
        return
    _logger.info(
        "Renaming legacy module %s -> %s in ir_model_data / ir_module_module",
        OLD_NAME, NEW_NAME,
    )
    # Drop legacy rows whose xmlid already exists under NEW_NAME, otherwise
    # the UPDATE below violates the (module, name) unique constraint.
    cr.execute(
        """
        DELETE FROM ir_model_data
         WHERE module = %s
           AND name IN (SELECT name FROM ir_model_data WHERE module = %s)
        """,
        (OLD_NAME, NEW_NAME),
    )
    cr.execute(
        "UPDATE ir_model_data SET module = %s WHERE module = %s",
        (NEW_NAME, OLD_NAME),
    )
    cr.execute(
        """
        DELETE FROM ir_module_module_dependency
         WHERE module_id IN (SELECT id FROM ir_module_module WHERE name = %s)
            OR name = %s
        """,
        (OLD_NAME, OLD_NAME),
    )
    cr.execute("DELETE FROM ir_module_module WHERE name = %s", (OLD_NAME,))


def _prune_orphan_xmlids(cr):
    """Delete ir_model_data rows under this module whose xmlid name is
    not in the current LEGITIMATE_XMLIDS set, and delete the records
    they point to."""
    cr.execute(
        """
        SELECT id, name, model, res_id
          FROM ir_model_data
         WHERE module = %s
        """,
        (NEW_NAME,),
    )
    rows = cr.fetchall()
    orphans = [(imd_id, name, model, res_id)
               for imd_id, name, model, res_id in rows
               if name not in LEGITIMATE_XMLIDS]
    if not orphans:
        return

    _logger.info(
        "Pruning %d orphan ir_model_data row(s) under %s",
        len(orphans), NEW_NAME,
    )

    # Group by model for batched deletes. Skip models that may not exist
    # anymore (legacy module removal).
    by_model = {}
    imd_ids = []
    for imd_id, _, model, res_id in orphans:
        imd_ids.append(imd_id)
        by_model.setdefault(model, []).append(res_id)

    for model, ids in by_model.items():
        table = model.replace('.', '_')
        cr.execute('SAVEPOINT cleanup_one')
        try:
            cr.execute(
                f'DELETE FROM "{table}" WHERE id = ANY(%s)',
                (ids,),
            )
            cr.execute('RELEASE SAVEPOINT cleanup_one')
        except Exception as e:
            _logger.warning(
                "Could not delete orphan rows in %s: %s", table, e,
            )
            cr.execute('ROLLBACK TO SAVEPOINT cleanup_one')

    cr.execute('DELETE FROM ir_model_data WHERE id = ANY(%s)', (imd_ids,))


def _cleanup(cr):
    _rename_legacy_module(cr)
    _prune_orphan_xmlids(cr)


def pre_init_hook(env):
    _cleanup(env.cr)


def migrate_cleanup(cr, version):
    """Called from migrations/19.0.1.2.0/post-migration.py."""
    del version  # required by Odoo migration API, not used
    _cleanup(cr)
